### ISSUE TITLE
docker installation error

### ISSUE THREAD

**Issue by craiten** [Volmarg/personal-management-system#133]
When following the instructions to install the PMS via docker on Linux (https://volmarg.github.io/docs/general/installation/docker/information) I get an error.
After logging in into the docker container and calling  `sh docker-first-run.sh`. I get the following error.

```
root@pPMS:/var/ww/pms# docker-compose exec php-fpm bash

root@7530de598fd7:/application# sh docker-first-run.sh

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

> SlowProg\CopyFile\ScriptHandler::copy
Copied file(s) from vendor_fixes/full_file_copy/specsharper/encrypt-bundle/ to vendor/specsharper/encrypt-bundle/.
> php -r "include_once 'installer//AutoInstaller.php'; use Installer\AutoInstaller; AutoInstaller::runDocker();" < /dev/tty


=================================================================================
sh: 1: node: not found
sh: 1: npm: not found
sh: 1: mysql: not found


        #########################################################################################################################
        #    This script will install and configure the project - make sure that You run this command as sudo. Despite the fact # 
        #    that this installer should handle most of things You will still need to do some things manually on the end.        # 
        #    Keep in mind that this is a simple one time run script - it won't check if You have already packages installed.    # 
        #    Some things just cannot be configured from the script, like the mysql configuration file in case of problems.      #
        #    There will be few attempts to solve some of the problems but You might be asked to do the backup on Your own.      #
        #                                                                                                                       #
        #    Make sure that You've run 'composer install' as sudo - this is a requirement!                                      #
        #    Also call 'composer install' ONLY from within the project root dir, otherwise You might mess up Your system        #
        #    As there are permissions being set to 'var' folder which is a subfolder of symfony project                         #
        #                                                                                                                       #
        #   Please install the composer dependencies first if You haven't made this yet!                                        #
        #########################################################################################################################
        

Basic requirements:

-------------------------------
Internet connection
Up to 500mb free space for production version
Up to 1gb free space for development version

-------------------------------


-------------------------------

Started configuring the database.
Database has been dropped (if You provided the existing one)
Database has been created
Creating database structure and inserting base data into the tables, please wait
Base data base been inserted into the tables
Finished configuring the database.

-------------------------------

Started creating folders.

Finished creating folders.

-------------------------------

Started building cache.

Finished building cache.

-------------------------------

Started setting permissions.
Owner for `var` folder has been set.
Group for `var` folder has been set.
Read, write, execute permissions for `var` folder have been set.
Owner for `vendor` folder has been set.
Group for `vendor` folder has been set.

Finished setting permissions.

-------------------------------

Started generating encryption key.

Fatal error: Uncaught TypeError: Argument 1 passed to Installer\Controller\Installer\InstallerController::setEncryptionKey() must be of the type string, null given, called in /application/installer/AutoInstaller.php on line 440 and defined in /application/installer/Controller/InstallerController.php:330
Stack trace:
#0 /application/installer/AutoInstaller.php(440): Installer\Controller\Installer\InstallerController::setEncryptionKey(NULL)
#1 /application/installer/AutoInstaller.php(111): Installer\AutoInstaller::generateEncryptionKey()
#2 Command line code(1): Installer\AutoInstaller::runDocker()
#3 {main}
  thrown in /application/installer/Controller/InstallerController.php on line 330
Script php -r "include_once 'installer//AutoInstaller.php'; use Installer\AutoInstaller; AutoInstaller::runDocker();" < /dev/tty handling the pms-installer-docker event returned with error code 255
chmod: cannot access '.env': No such file or directory
```

**Comment by ChrisQGeorge** [comment]
For a quick fix run composer update symfony/flex in the php-fpm container

**Comment by Volmarg** [comment]
I've updated the code, changes are in master. Flex was the issue indeed.
